"""
Live Performance Tracker.

Persists each set of picks generated by live_picks_v3 with timestamp
and entry prices. Periodically fetches current prices and computes:
  - Per-pick P&L (realized + unrealized)
  - Portfolio vs NIFTY benchmark (alpha)
  - Strategy hit-rate so far
  - Live regime annotations

This is how we answer "is my strategy actually working in live markets"
without relying on backtest hopes.
"""
from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

LEDGER_FILE = Path(__file__).resolve().parent.parent / "data" / "live_picks_ledger.json"
LEDGER_FILE.parent.mkdir(parents=True, exist_ok=True)


def _load_ledger() -> list[dict]:
    if not LEDGER_FILE.exists():
        return []
    try:
        with open(LEDGER_FILE, "r") as f:
            return json.load(f)
    except Exception:
        return []


def _save_ledger(records: list[dict]) -> None:
    try:
        with open(LEDGER_FILE, "w") as f:
            json.dump(records, f, indent=2, default=str)
    except Exception:
        pass


def record_picks(payload: dict, mark_as_invested: bool = False) -> dict:
    """
    Save the current pick set to the ledger.

    mark_as_invested=False: just track what was recommended (no real $)
    mark_as_invested=True: treat as actual deployment (user clicked
                            "I bought these")
    """
    ledger = _load_ledger()
    record = {
        "generated_at": int(time.time()),
        "generated_at_iso": datetime.now().isoformat(),
        "capital": payload.get("capital", 0),
        "engine": payload.get("engine", ""),
        "universe": payload.get("universe", ""),
        "mark_as_invested": mark_as_invested,
        "picks": [
            {
                "symbol": p["symbol"],
                "entry_price": p["current_price"],
                "target_qty": p["target_qty"],
                "target_value_inr": p["target_value_inr"],
                "sector": p.get("sector"),
                "composite_score": p.get("composite_score"),
                "target_weight_pct": p.get("target_weight_pct"),
            }
            for p in payload.get("picks", [])
        ],
        "status": "ACTIVE",
    }
    ledger.append(record)
    _save_ledger(ledger)
    return record


def fetch_current_prices(symbols: list[str]) -> dict[str, float]:
    """Get current close for a list of NSE symbols via yfinance."""
    from .data_loader import load_history
    prices = {}
    for sym in symbols:
        try:
            df = load_history(sym, period="1mo", use_cache=False)
            if not df.empty:
                prices[sym] = float(df["Close"].iloc[-1])
        except Exception:
            pass
    return prices


def evaluate_active(record: dict) -> dict:
    """Compute live P&L for one ledger record using current prices."""
    syms = [p["symbol"] for p in record["picks"]]
    prices = fetch_current_prices(syms)

    rows = []
    total_invested = 0
    total_value = 0
    for p in record["picks"]:
        sym = p["symbol"]
        cur = prices.get(sym)
        invested = p["target_qty"] * p["entry_price"]
        total_invested += invested
        if cur is None:
            rows.append({
                "symbol": sym,
                "entry": p["entry_price"],
                "current": None,
                "value": invested,
                "pnl_inr": 0,
                "pnl_pct": 0,
                "weight_pct": p.get("target_weight_pct", 0),
            })
            total_value += invested
            continue
        value = p["target_qty"] * cur
        total_value += value
        rows.append({
            "symbol": sym,
            "entry": p["entry_price"],
            "current": cur,
            "value": value,
            "pnl_inr": value - invested,
            "pnl_pct": (cur / p["entry_price"] - 1) * 100,
            "weight_pct": p.get("target_weight_pct", 0),
        })

    # NIFTY benchmark over same period
    from .market_timing_analyzer import _fetch_nifty
    nifty = _fetch_nifty()
    nifty_alpha = None
    nifty_return_pct = None
    if not nifty.empty:
        start_ts = pd.Timestamp(record["generated_at_iso"])
        sub = nifty[nifty.index >= start_ts]
        if not sub.empty:
            nifty_start = float(sub["Close"].iloc[0])
            nifty_end = float(sub["Close"].iloc[-1])
            nifty_return_pct = (nifty_end / nifty_start - 1) * 100
            portfolio_return_pct = (total_value / total_invested - 1) * 100 if total_invested > 0 else 0
            nifty_alpha = portfolio_return_pct - nifty_return_pct

    days_held = (datetime.now() - pd.Timestamp(record["generated_at_iso"])).days
    return {
        "generated_at": record["generated_at_iso"],
        "days_held": days_held,
        "engine": record.get("engine"),
        "mark_as_invested": record.get("mark_as_invested", False),
        "total_invested": total_invested,
        "current_value": total_value,
        "total_pnl_inr": total_value - total_invested,
        "total_pnl_pct": (total_value / total_invested - 1) * 100 if total_invested > 0 else 0,
        "nifty_return_pct": nifty_return_pct,
        "alpha_vs_nifty_pct": nifty_alpha,
        "picks": rows,
    }


def evaluate_all() -> dict:
    """Evaluate every recorded pick set."""
    ledger = _load_ledger()
    if not ledger:
        return {"records": [], "summary": {}}
    evaluations = [evaluate_active(r) for r in ledger]
    # Summary across all
    invested_total = [e for e in evaluations if e.get("mark_as_invested")]
    summary = {
        "n_pick_sets": len(evaluations),
        "n_invested": len(invested_total),
        "lifetime_alpha_avg": (np.mean([e["alpha_vs_nifty_pct"] for e in invested_total
                                          if e.get("alpha_vs_nifty_pct") is not None])
                                 if invested_total else None),
        "lifetime_return_avg": (np.mean([e["total_pnl_pct"] for e in invested_total])
                                  if invested_total else None),
    }
    return {"records": evaluations, "summary": summary}


def mark_invested(record_index: int) -> dict:
    """Flip a ledger record to mark_as_invested=True (user clicked buy)."""
    ledger = _load_ledger()
    if 0 <= record_index < len(ledger):
        ledger[record_index]["mark_as_invested"] = True
        _save_ledger(ledger)
        return {"ok": True, "record": ledger[record_index]}
    return {"error": "invalid index"}


def reset_ledger() -> dict:
    """Wipe all tracking."""
    if LEDGER_FILE.exists():
        LEDGER_FILE.unlink()
    return {"ok": True}
